# API credentials for Reddit
REDDIT_CLIENT_ID = "7tcPzKPK9UuUKoCKfnqxmw"
REDDIT_CLIENT_SECRET = "xekFE_8ae9uilz3rzcyN4kVkdlPR_g"
REDDIT_USER_AGENT = "Beautiful-Drag679"

# API credentials for Twitter
TWITTER_API_KEY = "da8ZD7bL84tGuAqTEu468dGnN"
TWITTER_API_SECRET_KEY = "Vg8Duqb1djqYcbgOGouEwAost6sCP2lyeThHUPIc3Ardf0EVhw"
TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAFsarQEAAAAAiL%2B%2FGT%2B6U7FroetniS%2BTfblFyRg%3DJNK1xQhXWU7jENHr4ZY2FojHgnDQlFBDK61AfbqVnoseJH2WJv"
TWITTER_ACCESS_TOKEN = "1730028224045084672-gruFDrShRpBPQqH7FD116Xm67vZOb0"
TWITTER_ACCESS_TOKEN_SECRET = "VHpcvKHNmWx0TlEt9LUgkGrhj5Yiv1mqOspjiNblAJrvg"

# Twitter API v2 credentials
TWITTER_CLIENT_ID = "azBtb01zbjhNWTRScHdTejNneG46MTpjaQ"
TWITTER_CLIENT_SECRET = "sqq-yVmyGqCS2zkcxFMbl-T5isG3TOKByUJ10gQyvqvC-8Xve9"



# API credentials for YouTube
YOUTUBE_API_KEY = "AIzaSyAvN-JwdYrWuj2ReBZ7IpqEVlZi4tRKSTs"
